name: Build Mobile Debug Staging

on:
  push:
    branches:
      # Only run when there's a push / commits on main branch
      - "staging"
    paths:
      - "mobile/**"

jobs: 
  BuildDebug:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: "./mobile"
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Setup Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Create Tags
        id: tags
        run: echo "::set-output name=sha_short::${GITHUB_SHA::7}" 
      
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"

      - name: Decoding android/key.properties
        run: echo "${{ secrets.KEYPROP_PROD }}" | base64 --decode > android/key.properties

      - name: Decoding android/app/travelliu.jks
        run: echo "${{ secrets.KEYJKS_PROD }}" | base64 --decode > android/app/travelliu.jks

      - name: Setup Java and JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      
      - name: "Build Mobile - Android"
        run: |
          flutter pub get
          flutter build apk --debug
      
      - name: "Prepare artifacts"
        run: |
          mkdir artifacts
          mv ./build/app/outputs/flutter-apk/app-debug.apk ./artifacts/travelliu-debug.apk
      
      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          name: "Debug Auto Build - ${{ steps.date.outputs.date }}"
          tag: ${{ steps.tags.outputs.sha_short }}
          commit: "main"
          artifacts: "mobile/artifacts/*.apk"
          body: "An auto build on staging at ${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
